/**
 * Mayobe Bros — Production XML Sitemap System
 * Mirrors the structure of RankMath's sitemap_index.xml
 *
 * Routes served:
 *   GET /sitemap.xml                 → Sitemap index
 *   GET /authoritative-sitemap.xml   → Static/authority pages
 *   GET /posts-sitemap{n}.xml        → Paginated post URLs (200 per file)
 *   GET /category-sitemap{n}.xml     → Categories + labels
 *   GET /image-sitemap{n}.xml        → Image sitemap with image:image tags
 *   GET /video-sitemap{n}.xml        → Video sitemap with video:video tags
 *   GET /sitemap-status              → JSON health & cache report
 */

import { Router, Request, Response } from 'express';
import { getSupabaseClient } from '../utils/supabase.js';
import {
  fromCache, toCache, getCacheEntries,
  URLS_PER_SITEMAP,
} from '../utils/sitemapCache.js';

const router = Router();

const SITE_URL = 'https://www.mayobebros.com';

// ── XML building helpers ──────────────────────────────────────────────────────

function escapeXml(s: string): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function isoDate(d: string | null | undefined): string {
  if (!d) return new Date().toISOString();
  try { return new Date(d).toISOString(); } catch { return new Date().toISOString(); }
}

function xmlDeclaration(): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>`,
    `<!-- Sitemap generated by Mayobe Bros CMS (mayobebros.com) -->`,
    `<!-- Powered by Mayobe Bros SEO Engine -->`,
  ].join('\n');
}

interface SitemapEntry { loc: string; lastmod: string }

function buildSitemapIndex(entries: SitemapEntry[]): string {
  const items = entries.map(e =>
    [
      '  <sitemap>',
      `    <loc>${escapeXml(e.loc)}</loc>`,
      `    <lastmod>${e.lastmod}</lastmod>`,
      '  </sitemap>',
    ].join('\n')
  ).join('\n');

  return [
    xmlDeclaration(),
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    items,
    '</sitemapindex>',
    `<!-- Generated: ${new Date().toISOString()} | Entries: ${entries.length} -->`,
  ].join('\n');
}

interface UrlEntry {
  loc: string;
  lastmod?: string;
  changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: string;
  image?: { loc: string; title: string; caption?: string; geoLocation?: string };
  video?: {
    thumbnailLoc?: string;
    title: string;
    description: string;
    contentLoc: string;
    playerLoc?: string;
    duration?: number;
    publicationDate?: string;
    familyFriendly?: boolean;
  };
  news?: {
    publication: string;
    language: string;
    publicationDate: string;
    title: string;
    keywords?: string;
  };
}

const NS_IMAGE = 'xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"';
const NS_VIDEO = 'xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"';
const NS_BASE  = 'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"';

function buildUrlset(entries: UrlEntry[], useImage = false, useVideo = false): string {
  const ns = [NS_BASE, useImage ? NS_IMAGE : '', useVideo ? NS_VIDEO : ''].filter(Boolean).join(' ');

  const items = entries.map(e => {
    const lines = ['  <url>'];
    lines.push(`    <loc>${escapeXml(e.loc)}</loc>`);
    if (e.lastmod)    lines.push(`    <lastmod>${isoDate(e.lastmod)}</lastmod>`);
    if (e.changefreq) lines.push(`    <changefreq>${e.changefreq}</changefreq>`);
    if (e.priority)   lines.push(`    <priority>${e.priority}</priority>`);

    if (e.image) {
      lines.push('    <image:image>');
      lines.push(`      <image:loc>${escapeXml(e.image.loc)}</image:loc>`);
      lines.push(`      <image:title>${escapeXml(e.image.title)}</image:title>`);
      if (e.image.caption)     lines.push(`      <image:caption>${escapeXml(e.image.caption)}</image:caption>`);
      if (e.image.geoLocation) lines.push(`      <image:geo_location>${escapeXml(e.image.geoLocation)}</image:geo_location>`);
      lines.push('    </image:image>');
    }

    if (e.video) {
      lines.push('    <video:video>');
      if (e.video.thumbnailLoc)    lines.push(`      <video:thumbnail_loc>${escapeXml(e.video.thumbnailLoc)}</video:thumbnail_loc>`);
      lines.push(`      <video:title>${escapeXml(e.video.title)}</video:title>`);
      lines.push(`      <video:description>${escapeXml(e.video.description)}</video:description>`);
      lines.push(`      <video:content_loc>${escapeXml(e.video.contentLoc)}</video:content_loc>`);
      if (e.video.playerLoc)       lines.push(`      <video:player_loc>${escapeXml(e.video.playerLoc)}</video:player_loc>`);
      if (e.video.duration != null) lines.push(`      <video:duration>${e.video.duration}</video:duration>`);
      if (e.video.publicationDate) lines.push(`      <video:publication_date>${isoDate(e.video.publicationDate)}</video:publication_date>`);
      lines.push(`      <video:family_friendly>${e.video.familyFriendly !== false ? 'yes' : 'no'}</video:family_friendly>`);
      lines.push('    </video:video>');
    }

    lines.push('  </url>');
    return lines.join('\n');
  }).join('\n');

  return [
    xmlDeclaration(),
    `<urlset ${ns}>`,
    items,
    '</urlset>',
    `<!-- Generated: ${new Date().toISOString()} | URLs: ${entries.length} -->`,
  ].join('\n');
}

function sendXml(res: Response, xml: string): void {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400');
  res.setHeader('X-Robots-Tag', 'noindex, nofollow');
  res.setHeader('Vary', 'Accept-Encoding');
  res.send(xml);
}

function notFound(res: Response): void {
  res.status(404).send('<?xml version="1.0" encoding="UTF-8"?><error>Sitemap page not found</error>');
}

function chunkArray<T>(arr: T[], size: number): T[][] {
  const result: T[][] = [];
  for (let i = 0; i < arr.length; i += size) result.push(arr.slice(i, i + size));
  return result;
}

function pageFromRegex(req: Request): number {
  const n = parseInt(req.params[0] ?? '1', 10);
  return isNaN(n) || n < 1 ? 0 : n;
}

// Build a post's canonical URL
function postUrl(catSlug: string, labelSlug: string | undefined, postSlug: string): string {
  return labelSlug
    ? `${SITE_URL}/post/${catSlug}/${labelSlug}/${postSlug}`
    : `${SITE_URL}/post/${catSlug}/${postSlug}`;
}

// ── Search Engine Ping ────────────────────────────────────────────────────────
// (uses existing searchPing utility; also exposes a direct ping for sitemap updates)

export async function pingSitemapUpdate(): Promise<void> {
  const encoded = encodeURIComponent(`${SITE_URL}/sitemap.xml`);
  const targets = [
    `https://www.google.com/ping?sitemap=${encoded}`,
    `https://www.bing.com/ping?sitemap=${encoded}`,
  ];
  await Promise.allSettled(
    targets.map(url =>
      fetch(url, {
        headers: { 'User-Agent': 'MayobeBros-SEO-Bot/1.0' },
        signal: AbortSignal.timeout(8000),
      }).catch(() => {})
    )
  );
  console.log(`[Sitemap] Pinged search engines: ${new Date().toISOString()}`);
}

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 1: SITEMAP INDEX  → /sitemap.xml
// Lists all child sitemaps dynamically based on content counts.
// ─────────────────────────────────────────────────────────────────────────────

router.get('/sitemap.xml', async (_req, res) => {
  try {
    const cacheKey = 'index';
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();

    // Run all counts in parallel
    const [
      { count: totalPosts },
      { count: totalCats },
      { count: totalLabels },
      { count: imgPosts },
      { data: latestPost },
      { data: latestCat },
    ] = await Promise.all([
      supabase.from('posts').select('*', { count: 'exact', head: true }).eq('status', 'published'),
      supabase.from('categories').select('*', { count: 'exact', head: true }),
      supabase.from('labels').select('*', { count: 'exact', head: true }),
      supabase.from('posts').select('*', { count: 'exact', head: true }).eq('status', 'published').not('featured_image', 'is', null),
      supabase.from('posts').select('updated_at, published_at').eq('status', 'published').order('updated_at', { ascending: false }).limit(1),
      supabase.from('categories').select('updated_at').order('updated_at', { ascending: false }).limit(1),
    ]);

    const now = new Date().toISOString();
    const latestPostDate = latestPost?.[0]?.updated_at || latestPost?.[0]?.published_at || now;
    const latestCatDate  = latestCat?.[0]?.updated_at || now;

    const postPages  = Math.max(1, Math.ceil((totalPosts  || 0) / URLS_PER_SITEMAP));
    const catPages   = Math.max(1, Math.ceil(((totalCats || 0) + (totalLabels || 0)) / URLS_PER_SITEMAP));
    const imgPages   = Math.max(1, Math.ceil((imgPosts   || 0) / URLS_PER_SITEMAP));

    const entries: SitemapEntry[] = [];

    // 1. Authoritative pages (highest priority, always first)
    entries.push({ loc: `${SITE_URL}/authoritative-sitemap.xml`, lastmod: isoDate(now) });

    // 2. Post sitemaps (paginated)
    for (let i = 1; i <= postPages; i++) {
      entries.push({
        loc: `${SITE_URL}/posts-sitemap${i}.xml`,
        lastmod: isoDate(i === 1 ? latestPostDate : now),
      });
    }

    // 3. Category sitemaps (paginated)
    for (let i = 1; i <= catPages; i++) {
      entries.push({ loc: `${SITE_URL}/category-sitemap${i}.xml`, lastmod: isoDate(latestCatDate) });
    }

    // 4. Image sitemaps (paginated, only if images exist)
    if ((imgPosts || 0) > 0) {
      for (let i = 1; i <= imgPages; i++) {
        entries.push({ loc: `${SITE_URL}/image-sitemap${i}.xml`, lastmod: isoDate(latestPostDate) });
      }
    }

    // 5. Video sitemap (always include; may be empty if no videos found)
    entries.push({ loc: `${SITE_URL}/video-sitemap1.xml`, lastmod: isoDate(now) });

    // 6. Google News sitemap (last 48h of articles)
    entries.push({ loc: `${SITE_URL}/news-sitemap.xml`, lastmod: isoDate(latestPostDate) });

    const xml = buildSitemapIndex(entries);
    toCache(cacheKey, xml, entries.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error('[Sitemap] Index error:', err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Sitemap generation failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 2: AUTHORITATIVE PAGES  → /authoritative-sitemap.xml
// Homepage, about, contact, policies — all priority 1.0 or 0.8+
// ─────────────────────────────────────────────────────────────────────────────

router.get('/authoritative-sitemap.xml', async (_req, res) => {
  try {
    const cacheKey = 'authoritative';
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const now = new Date().toISOString();

    const pages: UrlEntry[] = [
      { loc: `${SITE_URL}/`,                      changefreq: 'hourly',  priority: '1.0', lastmod: now },
      { loc: `${SITE_URL}/popular-posts`,          changefreq: 'daily',   priority: '0.9', lastmod: now },
      { loc: `${SITE_URL}/about`,                  changefreq: 'monthly', priority: '0.8', lastmod: now },
      { loc: `${SITE_URL}/contact`,                changefreq: 'monthly', priority: '0.8', lastmod: now },
      { loc: `${SITE_URL}/advertise`,              changefreq: 'monthly', priority: '0.7', lastmod: now },
      { loc: `${SITE_URL}/privacy-policy`,         changefreq: 'yearly',  priority: '0.5', lastmod: now },
      { loc: `${SITE_URL}/terms-of-service`,       changefreq: 'yearly',  priority: '0.5', lastmod: now },
      { loc: `${SITE_URL}/cookie-policy`,          changefreq: 'yearly',  priority: '0.5', lastmod: now },
      { loc: `${SITE_URL}/editorial-policy`,       changefreq: 'yearly',  priority: '0.5', lastmod: now },
      { loc: `${SITE_URL}/fact-checking-policy`,   changefreq: 'yearly',  priority: '0.5', lastmod: now },
      { loc: `${SITE_URL}/cache-policy`,           changefreq: 'yearly',  priority: '0.4', lastmod: now },
    ];

    // Pull any published static pages from DB
    const supabase = getSupabaseClient();
    const { data: dbPages } = await supabase
      .from('static_pages')
      .select('slug, updated_at')
      .eq('status', 'published')
      .limit(200);

    for (const p of dbPages || []) {
      const url = `${SITE_URL}/page/${p.slug}`;
      if (!pages.find(e => e.loc === url)) {
        pages.push({
          loc: url,
          lastmod: isoDate(p.updated_at),
          changefreq: 'monthly',
          priority: '0.6',
        });
      }
    }

    const xml = buildUrlset(pages);
    toCache(cacheKey, xml, pages.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error('[Sitemap] Authoritative error:', err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 3: POSTS SITEMAPS  → /posts-sitemap{n}.xml
// Paginated post URLs. 200 per file. Auto-increments.
// ─────────────────────────────────────────────────────────────────────────────

router.get(/^\/posts-sitemap(\d+)\.xml$/, async (req, res) => {
  const page = pageFromRegex(req);
  if (!page) return notFound(res);

  try {
    const cacheKey = `posts-${page}`;
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();
    const offset = (page - 1) * URLS_PER_SITEMAP;

    const { data: posts, error } = await supabase
      .from('posts')
      .select('slug, updated_at, published_at, title, featured_image, categories(slug, name), labels(slug)')
      .eq('status', 'published')
      .order('published_at', { ascending: false })
      .range(offset, offset + URLS_PER_SITEMAP - 1);

    if (error) throw error;
    if (!posts || posts.length === 0) return notFound(res);

    const entries: UrlEntry[] = [];
    const hasImages = posts.some(p => p.featured_image);

    for (const post of posts) {
      const catSlug   = (post.categories as any)?.slug;
      const labelSlug = (post.labels as any)?.slug;
      if (!catSlug) continue;

      const entry: UrlEntry = {
        loc:        postUrl(catSlug, labelSlug, post.slug),
        lastmod:    isoDate(post.updated_at || post.published_at),
        changefreq: 'daily',
        priority:   '0.8',
      };

      // Embed featured image inline in the URL entry
      if (post.featured_image) {
        entry.image = {
          loc:   post.featured_image,
          title: post.title || post.slug,
        };
      }

      entries.push(entry);
    }

    const xml = buildUrlset(entries, hasImages);
    toCache(cacheKey, xml, entries.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error(`[Sitemap] Posts page ${page} error:`, err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 4: CATEGORY SITEMAPS  → /category-sitemap{n}.xml
// All categories + all category/label combinations.
// ─────────────────────────────────────────────────────────────────────────────

router.get(/^\/category-sitemap(\d+)\.xml$/, async (req, res) => {
  const page = pageFromRegex(req);
  if (!page) return notFound(res);

  try {
    const cacheKey = `category-${page}`;
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();
    const now = new Date().toISOString();

    const [{ data: categories }, { data: labels }] = await Promise.all([
      supabase.from('categories').select('slug, name, updated_at').order('name'),
      supabase.from('labels').select('slug, name, category_id, updated_at, categories(slug)').order('name'),
    ]);

    const allEntries: UrlEntry[] = [];

    // Category index pages
    for (const cat of categories || []) {
      allEntries.push({
        loc:        `${SITE_URL}/category/${cat.slug}`,
        lastmod:    isoDate(cat.updated_at || now),
        changefreq: 'weekly',
        priority:   '0.7',
      });
    }

    // Category → label sub-pages
    const seenKeys = new Set<string>();
    for (const label of labels || []) {
      const catSlug = (label.categories as any)?.slug;
      if (!catSlug) continue;
      const key = `${catSlug}/${label.slug}`;
      if (seenKeys.has(key)) continue;
      seenKeys.add(key);
      allEntries.push({
        loc:        `${SITE_URL}/category/${catSlug}/${label.slug}`,
        lastmod:    isoDate(label.updated_at || now),
        changefreq: 'weekly',
        priority:   '0.6',
      });
    }

    const pages = chunkArray(allEntries, URLS_PER_SITEMAP);
    const pageEntries = pages[page - 1];
    if (!pageEntries || pageEntries.length === 0) return notFound(res);

    const xml = buildUrlset(pageEntries);
    toCache(cacheKey, xml, pageEntries.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error(`[Sitemap] Category page ${page} error:`, err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 5: IMAGE SITEMAPS  → /image-sitemap{n}.xml
// Dedicated image sitemap with image:image tags. Extracts both featured images
// AND inline <img> tags from post content.
// ─────────────────────────────────────────────────────────────────────────────

const IMAGE_PATTERN = /(?:src|data-src)="(https?:\/\/[^"]+\.(?:jpg|jpeg|png|gif|webp|avif|svg)(?:\?[^"]*)?)/gi;

router.get(/^\/image-sitemap(\d+)\.xml$/, async (req, res) => {
  const page = pageFromRegex(req);
  if (!page) return notFound(res);

  try {
    const cacheKey = `image-${page}`;
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();

    // Fetch posts that have at least a featured image (for pagination)
    const offset = (page - 1) * URLS_PER_SITEMAP;
    const { data: posts, error } = await supabase
      .from('posts')
      .select('slug, updated_at, published_at, title, featured_image, content, categories(slug), labels(slug)')
      .eq('status', 'published')
      .not('featured_image', 'is', null)
      .order('published_at', { ascending: false })
      .range(offset, offset + URLS_PER_SITEMAP - 1);

    if (error) throw error;
    if (!posts || posts.length === 0) return notFound(res);

    const entries: UrlEntry[] = [];
    const seenImages = new Set<string>();

    for (const post of posts) {
      const catSlug   = (post.categories as any)?.slug;
      const labelSlug = (post.labels as any)?.slug;
      if (!catSlug) continue;

      const pageUrlStr = postUrl(catSlug, labelSlug, post.slug);
      const lastmod    = isoDate(post.updated_at || post.published_at);

      // Featured image
      if (post.featured_image && !seenImages.has(post.featured_image)) {
        seenImages.add(post.featured_image);
        entries.push({
          loc:        pageUrlStr,
          lastmod,
          changefreq: 'monthly',
          priority:   '0.5',
          image: {
            loc:     post.featured_image,
            title:   post.title || post.slug,
            caption: post.title,
          },
        });
      }

      // Extract inline images from HTML content (max 5 per post to stay lean)
      if (post.content) {
        const matches = [...post.content.matchAll(IMAGE_PATTERN)].slice(0, 5);
        for (const m of matches) {
          const imgUrl = m[1];
          if (!imgUrl || seenImages.has(imgUrl) || imgUrl === post.featured_image) continue;
          seenImages.add(imgUrl);
          entries.push({
            loc:        pageUrlStr,
            lastmod,
            changefreq: 'monthly',
            priority:   '0.4',
            image: {
              loc:   imgUrl,
              title: post.title || post.slug,
            },
          });
        }
      }
    }

    if (entries.length === 0) return notFound(res);

    const xml = buildUrlset(entries, true);
    toCache(cacheKey, xml, entries.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error(`[Sitemap] Image page ${page} error:`, err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 6: VIDEO SITEMAPS  → /video-sitemap{n}.xml
// Detects YouTube embeds and direct video files inside post content.
// ─────────────────────────────────────────────────────────────────────────────

const YT_PATTERN   = /youtube(?:-nocookie)?\.com\/embed\/([a-zA-Z0-9_-]{11})/g;
const FILE_PATTERN = /src="(https?:\/\/[^"]+\.(?:mp4|webm|ogg)(?:\?[^"]*)?)"/gi;

router.get(/^\/video-sitemap(\d+)\.xml$/, async (req, res) => {
  const page = pageFromRegex(req);
  if (!page) return notFound(res);

  try {
    const cacheKey = `video-${page}`;
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();
    const { data: posts, error } = await supabase
      .from('posts')
      .select('slug, updated_at, published_at, title, content, featured_image, categories(slug), labels(slug)')
      .eq('status', 'published')
      .not('content', 'is', null)
      .order('published_at', { ascending: false })
      .limit(2000);

    if (error) throw error;

    const videoEntries: UrlEntry[] = [];
    const seenVideos = new Set<string>();

    for (const post of posts || []) {
      const catSlug   = (post.categories as any)?.slug;
      const labelSlug = (post.labels as any)?.slug;
      if (!catSlug || !post.content) continue;

      const pageUrlStr = postUrl(catSlug, labelSlug, post.slug);
      const lastmod    = isoDate(post.updated_at || post.published_at);
      const thumb      = post.featured_image || `${SITE_URL}/og-default.jpg`;

      // YouTube embeds
      const ytMatches = [...post.content.matchAll(YT_PATTERN)];
      for (const m of ytMatches) {
        const videoId  = m[1];
        const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
        if (seenVideos.has(watchUrl)) continue;
        seenVideos.add(watchUrl);

        videoEntries.push({
          loc:        pageUrlStr,
          lastmod,
          changefreq: 'monthly',
          priority:   '0.7',
          video: {
            thumbnailLoc:    `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
            title:           post.title || post.slug,
            description:     `Video in article: ${post.title}`,
            contentLoc:      watchUrl,
            playerLoc:       `https://www.youtube.com/embed/${videoId}`,
            publicationDate: post.published_at || undefined,
            familyFriendly:  true,
          },
        });
      }

      // Direct video files
      const fileMatches = [...post.content.matchAll(FILE_PATTERN)];
      for (const m of fileMatches) {
        const videoUrl = m[1];
        if (!videoUrl || seenVideos.has(videoUrl)) continue;
        seenVideos.add(videoUrl);

        videoEntries.push({
          loc:        pageUrlStr,
          lastmod,
          changefreq: 'monthly',
          priority:   '0.6',
          video: {
            thumbnailLoc:    thumb,
            title:           post.title || post.slug,
            description:     `Video in article: ${post.title}`,
            contentLoc:      videoUrl,
            publicationDate: post.published_at || undefined,
            familyFriendly:  true,
          },
        });
      }
    }

    // If no videos found at all, return an empty but valid sitemap
    const pages       = videoEntries.length > 0 ? chunkArray(videoEntries, URLS_PER_SITEMAP) : [[]];
    const pageEntries = pages[page - 1] ?? [];

    const xml = buildUrlset(pageEntries, false, true);
    toCache(cacheKey, xml, pageEntries.length);
    return sendXml(res, xml);
  } catch (err) {
    console.error(`[Sitemap] Video page ${page} error:`, err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 7: GOOGLE NEWS SITEMAP  → /news-sitemap.xml
// Last 48 hours of published posts for Google News inclusion.
// Google News only indexes articles published within the past 2 days.
// ─────────────────────────────────────────────────────────────────────────────

function buildNewsSitemap(entries: UrlEntry[]): string {
  const NS_NEWS  = 'xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"';
  const ns = [NS_BASE, NS_NEWS].join(' ');

  const items = entries.map(e => {
    if (!e.news) return '';
    const lines = ['  <url>'];
    lines.push(`    <loc>${escapeXml(e.loc)}</loc>`);
    if (e.lastmod) lines.push(`    <lastmod>${isoDate(e.lastmod)}</lastmod>`);
    lines.push('    <news:news>');
    lines.push('      <news:publication>');
    lines.push(`        <news:name>${escapeXml(e.news.publication)}</news:name>`);
    lines.push(`        <news:language>${escapeXml(e.news.language)}</news:language>`);
    lines.push('      </news:publication>');
    lines.push(`      <news:publication_date>${isoDate(e.news.publicationDate)}</news:publication_date>`);
    lines.push(`      <news:title>${escapeXml(e.news.title)}</news:title>`);
    if (e.news.keywords) lines.push(`      <news:keywords>${escapeXml(e.news.keywords)}</news:keywords>`);
    lines.push('    </news:news>');
    lines.push('  </url>');
    return lines.join('\n');
  }).filter(Boolean).join('\n');

  return [
    xmlDeclaration(),
    `<urlset ${ns}>`,
    items,
    '</urlset>',
    `<!-- Google News Sitemap | Generated: ${new Date().toISOString()} | Articles: ${entries.length} -->`,
  ].join('\n');
}

router.get('/news-sitemap.xml', async (_req, res) => {
  try {
    const cacheKey = 'news';
    const cached = fromCache(cacheKey);
    if (cached) return sendXml(res, cached);

    const supabase = getSupabaseClient();

    // Google News only cares about the last 2 days
    const cutoff = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();

    const { data: posts, error } = await supabase
      .from('posts')
      .select('slug, published_at, updated_at, title, excerpt, categories(slug), labels(slug)')
      .eq('status', 'published')
      .gte('published_at', cutoff)
      .order('published_at', { ascending: false })
      .limit(1000); // Google News max is 1000

    if (error) throw error;

    const entries: UrlEntry[] = [];

    for (const post of posts || []) {
      const catSlug   = (post.categories as any)?.slug;
      const labelSlug = (post.labels as any)?.slug;
      if (!catSlug) continue;

      entries.push({
        loc:     postUrl(catSlug, labelSlug, post.slug),
        lastmod: isoDate(post.updated_at || post.published_at),
        news: {
          publication:     'Mayobe Bros',
          language:        'en',
          publicationDate: post.published_at || post.updated_at || new Date().toISOString(),
          title:           post.title || post.slug,
          keywords:        undefined,
        },
      });
    }

    const xml = buildNewsSitemap(entries);
    // Cache news sitemap for only 15 min (freshness matters)
    toCache(cacheKey, xml, entries.length, 15 * 60 * 1000);
    return sendXml(res, xml);
  } catch (err) {
    console.error('[Sitemap] News error:', err);
    return res.status(500).send('<?xml version="1.0" encoding="UTF-8"?><error>Failed</error>');
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 9: SITEMAP STATUS  → /sitemap-status
// JSON health report: stats, cache state, all sitemap URLs.
// ─────────────────────────────────────────────────────────────────────────────

router.get('/sitemap-status', async (_req, res) => {
  try {
    const supabase = getSupabaseClient();

    const [
      { count: totalPosts },
      { count: totalCats },
      { count: totalLabels },
      { count: imgPosts },
    ] = await Promise.all([
      supabase.from('posts').select('*', { count: 'exact', head: true }).eq('status', 'published'),
      supabase.from('categories').select('*', { count: 'exact', head: true }),
      supabase.from('labels').select('*', { count: 'exact', head: true }),
      supabase.from('posts').select('*', { count: 'exact', head: true }).eq('status', 'published').not('featured_image', 'is', null),
    ]);

    const postPages = Math.max(1, Math.ceil((totalPosts  || 0) / URLS_PER_SITEMAP));
    const catPages  = Math.max(1, Math.ceil(((totalCats || 0) + (totalLabels || 0)) / URLS_PER_SITEMAP));
    const imgPages  = Math.max(1, Math.ceil((imgPosts   || 0) / URLS_PER_SITEMAP));

    return res.json({
      status:      'healthy',
      generatedAt: new Date().toISOString(),
      siteUrl:     SITE_URL,
      urlsPerSitemap: URLS_PER_SITEMAP,
      stats: {
        publishedPosts:   totalPosts  || 0,
        categories:       totalCats   || 0,
        labels:           totalLabels || 0,
        postsWithImages:  imgPosts    || 0,
        estimatedTotalUrls: (totalPosts || 0) + (totalCats || 0) + (totalLabels || 0) + 11,
      },
      sitemaps: {
        index:         `${SITE_URL}/sitemap.xml`,
        authoritative: `${SITE_URL}/authoritative-sitemap.xml`,
        posts:         Array.from({ length: postPages }, (_, i) => `${SITE_URL}/posts-sitemap${i + 1}.xml`),
        categories:    Array.from({ length: catPages  }, (_, i) => `${SITE_URL}/category-sitemap${i + 1}.xml`),
        images:        Array.from({ length: imgPages  }, (_, i) => `${SITE_URL}/image-sitemap${i + 1}.xml`),
        videos:        [`${SITE_URL}/video-sitemap1.xml`],
        news:          `${SITE_URL}/news-sitemap.xml`,
      },
      cache: {
        entries:    getCacheEntries().length,
        ttlSeconds: 3600,
        details:    getCacheEntries(),
      },
      robotsTxtEntry: `Sitemap: ${SITE_URL}/sitemap.xml`,
    });
  } catch (err) {
    return res.status(500).json({ status: 'error', error: String(err) });
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUTE 10: MANUAL PING TRIGGER  → POST /sitemap-ping
// For use by CMS admin to force-ping search engines.
// ─────────────────────────────────────────────────────────────────────────────

router.post('/sitemap-ping', async (_req, res) => {
  try {
    await pingSitemapUpdate();
    return res.json({ success: true, pingedAt: new Date().toISOString() });
  } catch (err) {
    return res.status(500).json({ success: false, error: String(err) });
  }
});

export default router;
