<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Sitemap — Mayobe Bros</title>
        <style>
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #0f172a;
            color: #e2e8f0;
            min-height: 100vh;
          }
          header {
            background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%);
            padding: 2rem 2rem 1.5rem;
            border-bottom: 1px solid #1e293b;
          }
          .header-inner {
            max-width: 1100px;
            margin: 0 auto;
            display: flex;
            align-items: center;
            gap: 1rem;
          }
          .logo { font-size: 1.5rem; font-weight: 800; color: #38bdf8; letter-spacing: -0.5px; }
          .subtitle { color: #94a3b8; font-size: 0.875rem; margin-top: 0.25rem; }
          .badge {
            background: #0ea5e9;
            color: #fff;
            font-size: 0.7rem;
            font-weight: 700;
            padding: 0.2rem 0.6rem;
            border-radius: 999px;
            letter-spacing: 0.05em;
            text-transform: uppercase;
            margin-left: auto;
          }
          main {
            max-width: 1100px;
            margin: 2rem auto;
            padding: 0 1.5rem;
          }
          .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
          }
          .stat-card {
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 10px;
            padding: 1rem 1.25rem;
          }
          .stat-card .num { font-size: 1.75rem; font-weight: 800; color: #38bdf8; }
          .stat-card .lbl { font-size: 0.75rem; color: #64748b; margin-top: 0.2rem; text-transform: uppercase; letter-spacing: 0.05em; }
          table {
            width: 100%;
            border-collapse: collapse;
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 12px;
            overflow: hidden;
          }
          thead { background: #0f172a; }
          th {
            padding: 0.85rem 1.25rem;
            text-align: left;
            font-size: 0.7rem;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #64748b;
            font-weight: 600;
            border-bottom: 1px solid #334155;
          }
          td {
            padding: 0.75rem 1.25rem;
            font-size: 0.875rem;
            border-bottom: 1px solid #1e293b;
            vertical-align: middle;
          }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #263347; }
          a { color: #38bdf8; text-decoration: none; }
          a:hover { text-decoration: underline; color: #7dd3fc; }
          .lastmod { color: #64748b; font-size: 0.8rem; white-space: nowrap; }
          .section-title {
            font-size: 0.85rem;
            font-weight: 700;
            color: #94a3b8;
            margin-bottom: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.06em;
          }
          .table-wrap { margin-bottom: 2.5rem; overflow-x: auto; }
          .priority-high { color: #4ade80; font-weight: 700; }
          .priority-med  { color: #facc15; }
          .priority-low  { color: #94a3b8; }
          footer {
            text-align: center;
            padding: 2rem;
            color: #334155;
            font-size: 0.75rem;
          }
        </style>
      </head>
      <body>
        <header>
          <div class="header-inner">
            <div>
              <div class="logo">Mayobe Bros</div>
              <div class="subtitle">XML Sitemap — Search Engine Index</div>
            </div>
            <span class="badge">Sitemap</span>
          </div>
        </header>

        <main>
          <xsl:apply-templates select="sitemap:sitemapindex"/>
          <xsl:apply-templates select="sitemap:urlset"/>
        </main>

        <footer>
          Generated by Mayobe Bros SEO Engine ·
          <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap) + count(sitemap:urlset/sitemap:url)"/> entries
        </footer>
      </body>
    </html>
  </xsl:template>

  <!-- ── SITEMAP INDEX ──────────────────────────────────────────────────── -->
  <xsl:template match="sitemap:sitemapindex">
    <div class="stats">
      <div class="stat-card">
        <div class="num"><xsl:value-of select="count(sitemap:sitemap)"/></div>
        <div class="lbl">Sitemap Files</div>
      </div>
    </div>

    <div class="table-wrap">
      <div class="section-title">Sitemap Index</div>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Sitemap URL</th>
            <th>Last Modified</th>
          </tr>
        </thead>
        <tbody>
          <xsl:for-each select="sitemap:sitemap">
            <tr>
              <td style="color:#475569;width:48px"><xsl:value-of select="position()"/></td>
              <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
              <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </div>
  </xsl:template>

  <!-- ── URL SET ────────────────────────────────────────────────────────── -->
  <xsl:template match="sitemap:urlset">
    <div class="stats">
      <div class="stat-card">
        <div class="num"><xsl:value-of select="count(sitemap:url)"/></div>
        <div class="lbl">URLs</div>
      </div>
    </div>

    <div class="table-wrap">
      <div class="section-title">URLs</div>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>URL</th>
            <th>Last Modified</th>
            <th>Change Freq</th>
            <th>Priority</th>
          </tr>
        </thead>
        <tbody>
          <xsl:for-each select="sitemap:url">
            <tr>
              <td style="color:#475569;width:48px"><xsl:value-of select="position()"/></td>
              <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
              <td class="lastmod"><xsl:value-of select="sitemap:lastmod"/></td>
              <td style="color:#64748b;font-size:0.8rem"><xsl:value-of select="sitemap:changefreq"/></td>
              <td>
                <xsl:choose>
                  <xsl:when test="sitemap:priority >= 0.8">
                    <span class="priority-high"><xsl:value-of select="sitemap:priority"/></span>
                  </xsl:when>
                  <xsl:when test="sitemap:priority >= 0.5">
                    <span class="priority-med"><xsl:value-of select="sitemap:priority"/></span>
                  </xsl:when>
                  <xsl:otherwise>
                    <span class="priority-low"><xsl:value-of select="sitemap:priority"/></span>
                  </xsl:otherwise>
                </xsl:choose>
              </td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </div>
  </xsl:template>

</xsl:stylesheet>
